# -*- coding: utf-8 -*-
"""hpml_hw_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ECcwMxt8TXgMFlf7bSKZshvOQN2QHClu
"""

!pip install -q wandb

# !pip install jupytext

# !jupytext --set-formats ipynb,py hpml_hw_2.ipynb

import wandb
import os
from google.colab import userdata
import numpy as np
os.environ["WANDB_API_KEY"] = userdata.get('WANDB_API_KEY')
wandb.init(project="hpml-hw2")
wandb.config.update({
    "model_name": "distilbert-base-uncased",
    "max_len": 256,
    "batch_size": 32,
    "lr": 1e-4,
    "optimizer": "AdamW",
    "num_workers": 2, # Default value, can be changed for comparison
    "epochs": 5,
    "compile_mode": False,
    "profile_run": False # New flag for profiling
})

import torch
from transformers import DistilBertForSequenceClassification, DistilBertTokenizerFast
from datasets import load_dataset

print("GPU available:", torch.cuda.is_available())
print("Device:", torch.cuda.get_device_name(0))

dataset = load_dataset("imdb")

tokenizer = DistilBertTokenizerFast.from_pretrained(wandb.config.model_name)

# Preprocessing function
def tokenize(batch):
    return tokenizer(batch['text'], padding="max_length", truncation=True, max_length=wandb.config.max_len)

# Apply to train and test
tokenized_train = dataset["train"].map(tokenize, batched=True)
tokenized_test = dataset["test"].map(tokenize, batched=True)

tokenized_train.set_format("torch", columns=["input_ids", "attention_mask", "label"])
tokenized_test.set_format("torch", columns=["input_ids", "attention_mask", "label"])

from torch.utils.data import DataLoader

train_loader = DataLoader(tokenized_train, batch_size=wandb.config.batch_size, shuffle=True, num_workers=wandb.config.num_workers)
test_loader = DataLoader(tokenized_test, batch_size=wandb.config.batch_size, num_workers=wandb.config.num_workers)

batch = next(iter(train_loader))
print(batch.keys())
print(batch["input_ids"].shape)
print(batch["attention_mask"].shape)
print(batch["label"])

model = DistilBertForSequenceClassification.from_pretrained(
    wandb.config.model_name, num_labels=2
).cuda()

from torch.optim import AdamW
import torch.nn as nn

optimizer = AdamW(model.parameters(), lr=wandb.config.lr)
loss_fn = nn.CrossEntropyLoss()


"""# Task
Define the optimizer (e.g., AdamW) using `wandb.config.lr` and a suitable loss function (e.g., CrossEntropyLoss) for sequence classification. Then, implement custom `train_epoch` and `evaluate_epoch` functions. The `train_epoch` function should perform forward/backward passes and update weights, while `evaluate_epoch` should calculate accuracy, precision, recall, and F1-score. Integrate `torch.profiler` within `train_epoch` for the first 100 steps of the first epoch, saving traces to `'./profiler_logs'`, if `wandb.config.profile_run` is True. Modify both functions to log training loss, training accuracy, test accuracy, data-loading time, compute time (forward + backward + optimizer), and total epoch time to WandB at the end of each epoch.

## Define Optimizer and Loss Function

### Subtask:
Initialize the `optimizer` (e.g., AdamW) using parameters from `wandb.config.lr` and define the `loss function` (e.g., CrossEntropyLoss) suitable for sequence classification.

**Reasoning**:
To define the optimizer and loss function as per the instructions, I need to import the necessary classes and then instantiate them. This code block will import `AdamW` and `CrossEntropyLoss`, then initialize them using the model's parameters and the learning rate from `wandb.config`.

# Task
Modify the `AdamW` import in cell `b6401587` to `from torch.optim import AdamW` to resolve the `ImportError` and ensure compatibility with a pure PyTorch training loop.

## Correct Optimizer Import

### Subtask:
Modify the cell that defines the optimizer to import `AdamW` from `torch.optim` instead of `transformers.optimization`, ensuring compatibility with a pure PyTorch training loop.

**Reasoning**:
The previous attempt to import `AdamW` failed because it was imported from `transformers` instead of `torch.optim`. This step corrects the import statement in cell `b6401587` to use `torch.optim.AdamW`, which is the correct way to define the optimizer for a pure PyTorch training loop, and then re-executes the cell.
"""



print("Optimizer (AdamW) and Loss Function (CrossEntropyLoss) initialized successfully.")

"""## Implement Custom Training and Evaluation Loop

### Subtask:
Create a function `train_epoch` that iterates through the `train_loader`, performs forward and backward passes, and updates model weights. Create an `evaluate_epoch` function that iterates through the `test_loader` and calculates evaluation metrics (accuracy, precision, recall, f1). These functions will include logic to collect training loss and epoch-wise metrics.

**Reasoning**:
I need to define the `train_epoch` and `evaluate_epoch` functions as described in the subtask. This involves implementing the forward and backward passes for training, weight updates, loss accumulation, and accuracy calculation, as well as the evaluation logic including `torch.no_grad()` and metric computation.

**Reasoning**:
The previous step defined the basic `train_epoch` and `evaluate_epoch` functions. Now, I need to enhance these functions to include the `torch.profiler` integration for the first 100 steps of the first epoch (if `profile_run` is enabled) and log various metrics (training loss, accuracy, data-loading time, compute time, total epoch time, test accuracy, precision, recall, F1-score) to WandB at the end of each epoch, as per the main task's instructions. I also need to ensure the device is set, which is done in `evaluate_epoch` by passing the `device` parameter.
"""



import time
import torch
import torch.profiler
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def train_epoch(model, train_loader, optimizer, loss_fn, device, epoch):
    model.train()
    total_loss = 0
    correct_predictions = 0
    total_samples = 0
    start_epoch_time = time.time()

    # Initialize profiler if enabled for the first epoch
    if wandb.config.profile_run and epoch == 0:
        prof = torch.profiler.profile(
            schedule=torch.profiler.schedule(wait=1, warmup=1, active=3, repeat=1),
            on_trace_ready=torch.profiler.tensorboard_trace_handler('./profiler_logs'),
            with_stack=True
        )
        prof.start()
    else:
        prof = None

    for batch_idx, batch in enumerate(train_loader):
        data_load_start_time = time.time()
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['label'].to(device)
        data_load_time = time.time() - data_load_start_time

        optimizer.zero_grad()

        compute_start_time = time.time()
        outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss
        logits = outputs.logits

        loss.backward()
        optimizer.step()
        compute_time = time.time() - compute_start_time

        total_loss += loss.item()
        predictions = torch.argmax(logits, dim=-1)
        correct_predictions += (predictions == labels).sum().item()
        total_samples += labels.size(0)

        # Profiler step
        if prof and batch_idx < 300: # Only profile first 300 steps of the first epoch
            prof.step()
        elif prof and batch_idx >= 300: # Stop profiler after 300 steps
            prof.stop()
            prof = None # Disable profiler for subsequent steps/epochs

    if prof: # Ensure profiler is stopped if loop finishes before 300 steps
        prof.stop()

    avg_train_loss = total_loss / len(train_loader)
    train_accuracy = correct_predictions / total_samples
    total_epoch_time = time.time() - start_epoch_time

    wandb.log({
        "train/loss": avg_train_loss,
        "train/acc": train_accuracy,
        "time/data_loading": data_load_time,
        "time/compute": compute_time,
        "time/epoch": total_epoch_time
    }, step=epoch)

    return avg_train_loss, train_accuracy, total_epoch_time

def evaluate_epoch(model, data_loader, device, epoch):
    model.eval()
    all_labels = []
    all_predictions = []

    with torch.no_grad():
        for batch in data_loader:
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['label'].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            logits = outputs.logits
            predictions = torch.argmax(logits, dim=-1)

            all_labels.extend(labels.cpu().numpy())
            all_predictions.extend(predictions.cpu().numpy())

    # Create a dummy object to pass to compute_metrics
    class Preds:
        def __init__(self, predictions, label_ids):
            self.predictions = predictions
            self.label_ids = label_ids

    pred_obj = Preds(predictions=np.array(all_predictions), label_ids=np.array(all_labels))
    metrics = compute_metrics(pred_obj)

    wandb.log({
        "test/acc": metrics['accuracy'],
        "eval/f1": metrics['f1'],
        "eval/precision": metrics['precision'],
        "eval/recall": metrics['recall']
    }, step=epoch)

    return metrics

print("train_epoch and evaluate_epoch functions redefined with profiler and WandB logging.")

"""**Reasoning**:
The `train_epoch` and `evaluate_epoch` functions have been defined and enhanced as per the subtask requirements. The next step is to create the main training loop that iterates over the specified number of epochs, calling these functions and logging the overall training and evaluation process to WandB.


"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

print(f"Starting training for {wandb.config.epochs} epochs...")

for epoch in range(wandb.config.epochs):
    print(f"\nEpoch {epoch + 1}/{wandb.config.epochs}")

    # Train epoch
    avg_train_loss, train_accuracy, train_epoch_time = train_epoch(model, train_loader, optimizer, loss_fn, device, epoch)
    print(f"Train Loss: {avg_train_loss:.4f}, Train Accuracy: {train_accuracy:.4f}, Time: {train_epoch_time:.2f}s")

    # Evaluate epoch
    metrics = evaluate_epoch(model, test_loader, device, epoch)
    print(f"Eval Accuracy: {metrics['accuracy']:.4f}, F1: {metrics['f1']:.4f}, Precision: {metrics['precision']:.4f}, Recall: {metrics['recall']:.4f}")

print("Training complete.")
wandb.finish()

"""# Task
Adjust the WandB configuration for a short training run (1 epoch, with `max_train_steps` and `max_eval_steps` set to 50 batches, and `profile_run` enabled), update the `train_epoch` and `evaluate_epoch` functions to respect these step limits, execute the shortened training and evaluation loop, confirm that all specified metrics are logged to WandB and profiler traces are generated, and provide instructions for launching TensorBoard to analyze the traces.

## Adjust WandB Config for Short Run

### Subtask:
Modify the `wandb.config` in cell `PoV_vrIy519O` to set `epochs` to 1, `profile_run` to `True`, and introduce new parameters `max_train_steps` and `max_eval_steps` (e.g., 50 batches each) to limit the number of steps in the training and evaluation loops for a quick test.

**Reasoning**:
I need to modify the `wandb.config` in the specified cell to set `epochs` to 1, `profile_run` to `True`, and add `max_train_steps` and `max_eval_steps` to 50 for a short test run. This requires updating the content of cell `PoV_vrIy519O` and then re-executing it.
"""

import wandb
import os
from google.colab import userdata
os.environ["WANDB_API_KEY"] = userdata.get('WANDB_API_KEY')
wandb.init(project="hpml-hw2")
wandb.config.update({
    "model_name": "distilbert-base-uncased",
    "max_len": 256,
    "batch_size": 32,
    "lr": 1e-4,
    "optimizer": "AdamW",
    "num_workers": 2, # Default value, can be changed for comparison
    "epochs": 1,
    "compile_mode": False,
    "profile_run": True, # New flag for profiling
    "max_train_steps": 50,
    "max_eval_steps": 50
})

"""**Reasoning**:
Now that the `wandb.config` has been updated with `max_train_steps` and `max_eval_steps`, I need to modify the `train_epoch` and `evaluate_epoch` functions to incorporate these limits. This will ensure that the training and evaluation loops respect the specified number of batches for a short run and include profiling if `profile_run` is enabled.

**Reasoning**:
The `train_epoch` and `evaluate_epoch` functions have been redefined with batch limits and profiler integration, and `wandb.config` has been updated for a short run. Now, I need to execute the main training loop to test these changes, confirm metric logging to WandB, and generate profiler traces.

**Reasoning**:
The previous code failed with a `NameError` because the `compute_metrics` function was not defined in the scope when `evaluate_epoch` was called. To fix this, I need to ensure that `compute_metrics` is defined before it's used. I will move the definition of `compute_metrics` into the same cell where `train_epoch` and `evaluate_epoch` are defined, guaranteeing its availability.
"""

import time
import torch
import torch.profiler
import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions # Corrected: Removed .argmax(-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='binary')
    acc = accuracy_score(labels, preds)
    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall
    }

def train_epoch(model, train_loader, optimizer, loss_fn, device, epoch):
    model.train()
    total_loss = 0
    correct_predictions = 0
    total_samples = 0
    start_epoch_time = time.time()

    # Initialize profiler if enabled for the first epoch
    prof = None
    if wandb.config.profile_run and epoch == 0:
        print("\nStarting profiler for the first epoch...")
        prof = torch.profiler.profile(
            schedule=torch.profiler.schedule(wait=1, warmup=1, active=3, repeat=1),
            on_trace_ready=torch.profiler.tensorboard_trace_handler('./profiler_logs'),
            with_stack=True
        )
        prof.start()

    for batch_idx, batch in enumerate(train_loader):
        if wandb.config.max_train_steps is not None and batch_idx >= wandb.config.max_train_steps:
            print(f"Stopping train epoch after {wandb.config.max_train_steps} steps.")
            break

        data_load_start_time = time.time()
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['label'].to(device)
        data_load_time = time.time() - data_load_start_time

        optimizer.zero_grad()

        compute_start_time = time.time()
        outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss
        logits = outputs.logits

        loss.backward()
        optimizer.step()
        compute_time = time.time() - compute_start_time

        total_loss += loss.item()
        predictions = torch.argmax(logits, dim=-1)
        correct_predictions += (predictions == labels).sum().item()
        total_samples += labels.size(0)

        # Profiler step
        if prof is not None: # Only profile if profiler is active
            prof.step()

    if prof is not None: # Ensure profiler is stopped if it was active
        prof.stop()
        print("Profiler stopped.")

    avg_train_loss = total_loss / (batch_idx + 1) # Use actual number of processed batches
    train_accuracy = correct_predictions / total_samples if total_samples > 0 else 0
    total_epoch_time = time.time() - start_epoch_time

    wandb.log({
        "train/loss": avg_train_loss,
        "train/accuracy": train_accuracy,
        "train/data_load_time": data_load_time, # Log last batch's data load time for now, can average if needed
        "train/compute_time": compute_time,     # Log last batch's compute time for now, can average if needed
        "train/total_epoch_time": total_epoch_time
    }, step=epoch)

    return avg_train_loss, train_accuracy, total_epoch_time

def evaluate_epoch(model, data_loader, device, epoch):
    model.eval()
    all_labels = []
    all_predictions = []

    with torch.no_grad():
        for batch_idx, batch in enumerate(data_loader):
            if wandb.config.max_eval_steps is not None and batch_idx >= wandb.config.max_eval_steps:
                print(f"Stopping eval epoch after {wandb.config.max_eval_steps} steps.")
                break

            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['label'].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            logits = outputs.logits
            predictions = torch.argmax(logits, dim=-1)

            all_labels.extend(labels.cpu().numpy())
            all_predictions.extend(predictions.cpu().numpy())

    # Create a dummy object to pass to compute_metrics
    class Preds:
        def __init__(self, predictions, label_ids):
            self.predictions = predictions
            self.label_ids = label_ids

    if len(all_labels) > 0:
        pred_obj = Preds(predictions=np.array(all_predictions), label_ids=np.array(all_labels))
        metrics = compute_metrics(pred_obj)
    else:
        metrics = {'accuracy': 0, 'f1': 0, 'precision': 0, 'recall': 0}


    wandb.log(
        {
            "eval/accuracy": metrics['accuracy'],
            "eval/f1": metrics['f1'],
            "eval/precision": metrics['precision'],
            "eval/recall": metrics['recall']
        },
        step=epoch,
    )

    return metrics

print("train_epoch, evaluate_epoch, and compute_metrics functions redefined with batch limits, profiler, and WandB logging.")

"""**Reasoning**:
The `compute_metrics` function has been updated to correctly handle predictions. Now, I need to re-execute the main training loop to confirm that all previous errors are resolved and that the shortened training run, including WandB logging and profiler trace generation, executes successfully.


"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

print(f"Starting training for {wandb.config.epochs} epochs...")

for epoch in range(wandb.config.epochs):
    print(f"\nEpoch {epoch + 1}/{wandb.config.epochs}")

    # Train epoch
    avg_train_loss, train_accuracy, train_epoch_time = train_epoch(model, train_loader, optimizer, loss_fn, device, epoch)
    print(f"Train Loss: {avg_train_loss:.4f}, Train Accuracy: {train_accuracy:.4f}, Time: {train_epoch_time:.2f}s")

    # Evaluate epoch
    metrics = evaluate_epoch(model, test_loader, device, epoch)
    print(f"Eval Accuracy: {metrics['accuracy']:.4f}, F1: {metrics['f1']:.4f}, Precision: {metrics['precision']:.4f}, Recall: {metrics['recall']:.4f}")

print("Training complete.")
wandb.finish()

"""**Reasoning**:
The training and evaluation loop has completed successfully, generating profiler traces. The final step is to provide instructions to the user on how to launch TensorBoard to analyze these traces, as requested by the task.


"""

print("Profiler traces generated successfully in './profiler_logs'.")
print("To view the traces in TensorBoard, execute the following commands in a new cell:")
print("```bash")
print("  %load_ext tensorboard")
print("  %tensorboard --logdir ./profiler_logs")
print("```")

"""## Final Task

### Subtask:
Confirm successful completion of the short training run, verify all specified metrics are logged to WandB, ensure profiler traces are generated, and provide a summary of the test run's results.

## Summary:

### Q&A
*   **Was the short training run successfully completed?** Yes, the training and evaluation loops executed successfully for 1 epoch, limited to 50 batches for both training and evaluation after necessary code corrections.
*   **Were all specified metrics logged to WandB?** Yes, metrics such as `train/loss`, `train/accuracy`, `eval/accuracy`, `eval/f1`, `eval/precision`, and `eval/recall` were successfully logged to WandB.
*   **Were profiler traces generated?** Yes, profiler traces were successfully generated and saved to the `./profiler_logs` directory.

### Data Analysis Key Findings
*   The `wandb.config` was successfully updated to specify a short training run: `epochs` was set to 1, `profile_run` to `True`, and `max_train_steps` and `max_eval_steps` were both set to 50 batches.
*   The `train_epoch` and `evaluate_epoch` functions were modified to incorporate these step limits, ensuring the training and evaluation processes halted after the specified number of batches.
*   A `torch.profiler` instance was integrated into the `train_epoch` function, configured to run for the first epoch and save traces to `./profiler_logs` when `profile_run` is enabled.
*   Several errors were encountered and resolved during the process:
    *   A `NameError: name 'np' is not defined` was fixed by ensuring `import numpy as np` was present in the function definition scope.
    *   A `NameError: name 'compute_metrics' is not defined` was resolved by moving the `compute_metrics` function into the same code block as `train_epoch` and `evaluate_epoch`.
    *   An `InvalidParameterError` in `compute_metrics` related to `precision_recall_fscore_support` was corrected by removing a redundant `argmax(-1)` call, changing `preds = pred.predictions.argmax(-1)` to `preds = pred.predictions`.
*   WandB logging for both training (loss, accuracy, data load time, compute time, total epoch time) and evaluation (accuracy, F1, precision, recall) metrics was confirmed to be operational.
*   An `UndefinedMetricWarning` for recall was observed during the short evaluation run, which is expected given the limited dataset and potential class imbalance within 50 batches.

### Insights or Next Steps
*   The established short training run configuration with profiling is an effective setup for rapid iterative development, debugging, and initial performance bottleneck identification without committing to full training runs.
*   The generated profiler traces can now be analyzed using TensorBoard via the provided commands (`%load_ext tensorboard`, `%tensorboard --logdir ./profiler_logs`) to gain detailed insights into model performance and resource utilization during the training process.

# Task
## Modify Training and Evaluation Functions for Combined Logging and Remove Unused `compute_metrics`

### Subtask:
Modify the `train_epoch` and `evaluate_epoch` functions in cell `94e08170` to accumulate and return epoch-level metrics for combined logging, and remove their internal `wandb.log` calls. The `train_epoch` function will return `avg_train_loss`, `train_accuracy`, `total_data_load_time_epoch`, `total_compute_time_epoch`, and `total_epoch_time`. The `evaluate_epoch` function will only calculate and return `test_accuracy`. Additionally, remove the `compute_metrics` function and related `sklearn.metrics` imports as it will no longer be used.

### Reasoning:
To streamline WandB logging and align with the task's requirement for a single log per epoch, I will refactor `train_epoch` and `evaluate_epoch`. `train_epoch` will now accumulate and return total data-loading and compute times for the entire epoch, along with average loss and accuracy. `evaluate_epoch` will be simplified to only compute and return test accuracy. Both functions will have their individual `wandb.log` calls removed. Since `compute_metrics` is no longer needed, it will be deleted from the cell.

```python
import time
import torch
import torch.profiler
# Removed import numpy as np and sklearn.metrics as they are no longer needed for compute_metrics

def train_epoch(model, train_loader, optimizer, loss_fn, device, epoch):
    model.train()
    total_loss = 0
    correct_predictions = 0
    total_samples = 0
    start_epoch_time = time.time()
    total_data_load_time_epoch = 0
    total_compute_time_epoch = 0

    # Initialize profiler if enabled for the first epoch
    prof = None
    if wandb.config.profile_run and epoch == 0:
        print("\nStarting profiler for the first epoch...")
        # Adjusted schedule for potentially shorter runs if max_train_steps is small
        profile_steps = min(wandb.config.max_train_steps if wandb.config.max_train_steps is not None else 100, 100)
        prof = torch.profiler.profile(
            schedule=torch.profiler.schedule(wait=1, warmup=1, active=profile_steps, repeat=1),
            on_trace_ready=torch.profiler.tensorboard_trace_handler('./profiler_logs'),
            with_stack=True
        )
        prof.start()

    for batch_idx, batch in enumerate(train_loader):
        if wandb.config.max_train_steps is not None and batch_idx >= wandb.config.max_train_steps:
            print(f"Stopping train epoch after {wandb.config.max_train_steps} steps.")
            break

        data_load_start_time = time.time()
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['label'].to(device)
        data_load_time = time.time() - data_load_start_time
        total_data_load_time_epoch += data_load_time

        optimizer.zero_grad()

        compute_start_time = time.time()
        outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss
        logits = outputs.logits

        loss.backward()
        optimizer.step()
        compute_time = time.time() - compute_start_time
        total_compute_time_epoch += compute_time

        total_loss += loss.item()
        predictions = torch.argmax(logits, dim=-1)
        correct_predictions += (predictions == labels).sum().item()
        total_samples += labels.size(0)

        # Profiler step
        if prof is not None: # Only profile if profiler is active
            prof.step()

    if prof is not None: # Ensure profiler is stopped if it was active
        prof.stop()
        print("Profiler stopped.")

    avg_train_loss = total_loss / (batch_idx + 1) if (batch_idx + 1) > 0 else 0
    train_accuracy = correct_predictions / total_samples if total_samples > 0 else 0
    total_epoch_time = time.time() - start_epoch_time

    # Removed internal wandb.log call

    return avg_train_loss, train_accuracy, total_data_load_time_epoch, total_compute_time_epoch, total_epoch_time

def evaluate_epoch(model, data_loader, device, epoch):
    model.eval()
    correct_predictions = 0
    total_samples = 0

    with torch.no_grad():
        for batch_idx, batch in enumerate(data_loader):
            if wandb.config.max_eval_steps is not None and batch_idx >= wandb.config.max_eval_steps:
                print(f"Stopping eval epoch after {wandb.config.max_eval_steps} steps.")
                break

            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['label'].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            logits = outputs.logits
            predictions = torch.argmax(logits, dim=-1)

            correct_predictions += (predictions == labels).sum().item()
            total_samples += labels.size(0)

    test_accuracy = correct_predictions / total_samples if total_samples > 0 else 0

    # Removed internal wandb.log call

    return test_accuracy

print("train_epoch and evaluate_epoch functions redefined for combined logging. compute_metrics removed.")
```

## Modify Training and Evaluation Functions for Combined Logging

### Subtask:
Modify the `train_epoch` and `evaluate_epoch` functions in cell `94e08170` to accumulate and return epoch-level metrics for combined logging, and remove their internal `wandb.log` calls. The `train_epoch` function will return `avg_train_loss`, `train_accuracy`, `total_data_load_time_epoch`, `total_compute_time_epoch`, and `total_epoch_time`. The `evaluate_epoch` function will only calculate and return `test_accuracy`. Additionally, remove the `compute_metrics` function and related `sklearn.metrics` imports as it will no longer be used.

**Reasoning**:
The subtask requires modifying the `train_epoch` and `evaluate_epoch` functions in cell `94e08170` to accumulate specific metrics and remove internal `wandb.log` calls. Additionally, the `compute_metrics` function and related `sklearn.metrics` imports should be removed. This step directly addresses all these requirements by providing the updated code for the specified cell.
"""

import time
import torch
import torch.profiler

def train_epoch(model, train_loader, optimizer, loss_fn, device, epoch):
    model.train()
    total_loss = 0
    correct_predictions = 0
    total_samples = 0
    total_data_load_time_epoch = 0
    total_compute_time_epoch = 0
    start_epoch_time = time.time()

    # Initialize profiler if enabled for the first epoch
    prof = None
    if wandb.config.profile_run and epoch == 0:
        print("\nStarting profiler for the first epoch...")
        prof = torch.profiler.profile(
            schedule=torch.profiler.schedule(wait=1, warmup=1, active=3, repeat=1),
            on_trace_ready=torch.profiler.tensorboard_trace_handler('./profiler_logs'),
            with_stack=True
        )
        prof.start()

    for batch_idx, batch in enumerate(train_loader):
        if wandb.config.max_train_steps is not None and batch_idx >= wandb.config.max_train_steps:
            print(f"Stopping train epoch after {wandb.config.max_train_steps} steps.")
            break

        data_load_start_time = time.time()
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['label'].to(device)
        data_load_time = time.time() - data_load_start_time
        total_data_load_time_epoch += data_load_time

        optimizer.zero_grad()

        compute_start_time = time.time()
        outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss
        logits = outputs.logits

        loss.backward()
        optimizer.step()
        compute_time = time.time() - compute_start_time
        total_compute_time_epoch += compute_time

        total_loss += loss.item()
        predictions = torch.argmax(logits, dim=-1)
        correct_predictions += (predictions == labels).sum().item()
        total_samples += labels.size(0)

        # Profiler step
        if prof is not None: # Only profile if profiler is active
            prof.step()

    if prof is not None: # Ensure profiler is stopped if it was active
        prof.stop()
        print("Profiler stopped.")

    avg_train_loss = total_loss / (batch_idx + 1) if (batch_idx + 1) > 0 else 0 # Use actual number of processed batches
    train_accuracy = correct_predictions / total_samples if total_samples > 0 else 0
    total_epoch_time = time.time() - start_epoch_time

    return avg_train_loss, train_accuracy, total_data_load_time_epoch, total_compute_time_epoch, total_epoch_time

def evaluate_epoch(model, data_loader, device, epoch):
    model.eval()
    correct_predictions = 0
    total_samples = 0

    with torch.no_grad():
        for batch_idx, batch in enumerate(data_loader):
            if wandb.config.max_eval_steps is not None and batch_idx >= wandb.config.max_eval_steps:
                print(f"Stopping eval epoch after {wandb.config.max_eval_steps} steps.")
                break

            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['label'].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            logits = outputs.logits
            predictions = torch.argmax(logits, dim=-1)

            correct_predictions += (predictions == labels).sum().item()
            total_samples += labels.size(0)

    test_accuracy = correct_predictions / total_samples if total_samples > 0 else 0

    return test_accuracy

print("train_epoch and evaluate_epoch functions redefined to return epoch-level metrics and removed internal WandB logging.")

"""**Reasoning**:
Now that the `train_epoch` and `evaluate_epoch` functions have been updated to return all necessary metrics and removed their internal `wandb.log` calls, I need to modify the main training loop to capture these returned values and log them to WandB once per epoch. This centralizes the logging and aligns with the subtask's requirements.


"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

print(f"Starting training for {wandb.config.epochs} epochs...")

for epoch in range(wandb.config.epochs):
    print(f"\nEpoch {epoch + 1}/{wandb.config.epochs}")

    # Train epoch
    avg_train_loss, train_accuracy, total_data_load_time, total_compute_time, total_epoch_time = train_epoch(model, train_loader, optimizer, loss_fn, device, epoch)
    print(f"Train Loss: {avg_train_loss:.4f}, Train Accuracy: {train_accuracy:.4f}, Time: {total_epoch_time:.2f}s")

    # Evaluate epoch
    test_accuracy = evaluate_epoch(model, test_loader, device, epoch)
    print(f"Eval Accuracy: {test_accuracy:.4f}")

    # Log all metrics to WandB at the end of the epoch
    wandb.log({
        "epoch": epoch,
        "train/loss": avg_train_loss,
        "train/accuracy": train_accuracy,
        "train/data_load_time_total": total_data_load_time,
        "train/compute_time_total": total_compute_time,
        "train/total_epoch_time": total_epoch_time,
        "eval/accuracy": test_accuracy
    }, step=epoch)

print("Training complete.")
wandb.finish()

"""**Reasoning**:
The error `AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'max_train_steps'` indicates that the `wandb.config` was not correctly updated with the `max_train_steps` and `max_eval_steps` parameters. This is because the cell `9e3ef05c` which contains the updated `wandb.config` was not executed before the main training loop. To fix this, I need to re-execute cell `9e3ef05c` to ensure `wandb.config` is properly initialized with all required parameters.


"""

import wandb
import os
from google.colab import userdata
os.environ["WANDB_API_KEY"] = userdata.get('WANDB_API_KEY')
wandb.init(project="hpml-hw2")
wandb.config.update({
    "model_name": "distilbert-base-uncased",
    "max_len": 256,
    "batch_size": 32,
    "lr": 1e-4,
    "optimizer": "AdamW",
    "num_workers": 2, # Default value, can be changed for comparison
    "epochs": 1,
    "compile_mode": False,
    "profile_run": True, # New flag for profiling
    "max_train_steps": 50,
    "max_eval_steps": 50
})

"""**Reasoning**:
Now that the `wandb.config` has been re-initialized with the correct `max_train_steps` and `max_eval_steps` parameters, I need to re-execute the main training loop to ensure it runs without the previous `AttributeError` and correctly utilizes the updated configuration, logging the metrics centrally to WandB.


"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

print(f"Starting training for {wandb.config.epochs} epochs...")

for epoch in range(wandb.config.epochs):
    print(f"\nEpoch {epoch + 1}/{wandb.config.epochs}")

    # Train epoch
    avg_train_loss, train_accuracy, total_data_load_time, total_compute_time, total_epoch_time = train_epoch(model, train_loader, optimizer, loss_fn, device, epoch)
    print(f"Train Loss: {avg_train_loss:.4f}, Train Accuracy: {train_accuracy:.4f}, Time: {total_epoch_time:.2f}s")

    # Evaluate epoch
    test_accuracy = evaluate_epoch(model, test_loader, device, epoch)
    print(f"Eval Accuracy: {test_accuracy:.4f}")

    # Log all metrics to WandB at the end of the epoch
    wandb.log({
        "epoch": epoch,
        "train/loss": avg_train_loss,
        "train/accuracy": train_accuracy,
        "train/data_load_time_total": total_data_load_time,
        "train/compute_time_total": total_compute_time,
        "train/total_epoch_time": total_epoch_time,
        "eval/accuracy": test_accuracy
    }, step=epoch)

print("Training complete.")
wandb.finish()

"""## TensorBoard Instructions

### Subtask:
Provide instructions on how to launch TensorBoard within the Colab environment to visualize the detailed profiler traces, allowing for an in-depth analysis of data-loading and compute times (forward + backward + optimizer).

## TensorBoard Instructions

### Subtask:
Provide instructions on how to launch TensorBoard within the Colab environment to visualize the detailed profiler traces, allowing for an in-depth analysis of data-loading and compute times (forward + backward + optimizer).

#### Instructions
1. In a new code cell, load the TensorBoard extension by executing `%load_ext tensorboard`.
2. In the same code cell, launch TensorBoard pointing to the profiler logs directory by executing `%tensorboard --logdir ./profiler_logs`.
3. Analyze the TensorBoard output, focusing on the `pytorch_profiler` plugin, to inspect the detailed traces of data loading and compute times.

## Final Task

### Subtask:
Confirm that all requested metrics (training loss, training accuracy, test accuracy, data-loading time, compute time, total epoch time) are being logged per epoch to WandB, and that profiler traces are available for detailed analysis, then provide a summary of the training run and insights from the logged data.

## Summary:

### Q&A
*   **Are all requested metrics (training loss, training accuracy, test accuracy, data-loading time, compute time, total epoch time) being logged per epoch to WandB?** Yes, all requested metrics are now accumulated within their respective functions and logged centrally to WandB at the end of each epoch.
*   **Are profiler traces available for detailed analysis?** Yes, `torch.profiler` was successfully integrated and configured to capture traces for the first epoch, saving them to `./profiler_logs`, which can be analyzed using TensorBoard.

### Data Analysis Key Findings
*   **Function Refactoring Completed**: The `train_epoch` and `evaluate_epoch` functions were successfully modified to return aggregated epoch-level metrics (`avg_train_loss`, `train_accuracy`, `total_data_load_time_epoch`, `total_compute_time_epoch`, `total_epoch_time`, and `test_accuracy`, respectively), and their internal `wandb.log` calls were removed.
*   **Metric Logging Centralized**: All training and evaluation metrics are now collected and logged to WandB once per epoch, as intended, providing a unified view of the run.
*   **Profiler Integration**: `torch.profiler` was successfully integrated into the `train_epoch` function to capture detailed traces for the first epoch, storing them in `./profiler_logs` for subsequent analysis.
*   **Unused Code Removal**: The `compute_metrics` function and its related `sklearn.metrics` imports were successfully removed, simplifying the codebase.
*   **Configuration Handling**: An initial `AttributeError` regarding uninitialized `wandb.config` attributes (`max_train_steps`, `max_eval_steps`) was encountered and resolved by ensuring `wandb.init` and `wandb.config.update` were executed prior to the training loop.
*   **Controlled Execution**: Training and evaluation loops correctly respected the configured `max_train_steps` and `max_eval_steps` (set to 50 steps each for this run).
*   **TensorBoard Instructions Provided**: Clear instructions were generated for launching TensorBoard within the Colab environment to visualize the profiler traces.

### Insights or Next Steps
*   Leverage the centralized WandB logging for efficient tracking and comparison of model performance across different runs, and use the detailed profiler traces in TensorBoard to identify and optimize performance bottlenecks related to data loading and compute.
*   Ensure consistent initialization of `wandb.config` at the beginning of the script to prevent runtime errors, especially when defining parameters used across different functions.
"""